### ISSUE TITLE
Added color tint and tried to do rotation during moves...

### ISSUE THREAD

**Issue by RedKrieg** [sunflowermans/TTS-UtilityMemoryBag#2]
Hi, I needed to save Alpha channel information with your bag, so I implemented that, then I took a pass at using rotation matrices to rotate during moves, but right now it only works reliably for the Y axis.  I can't figure out why my relative rotation calculation doesn't work if the source object is rotated in certain directions (Y=180 will invert X rotations, for example).  I'm sure I'm just not thinking through something, but I wanted to share my work in case I don't come back to it any time soon, on the off chance someone can find it useful.

https://github.com/RedKrieg/TTS-UtilityMemoryBag/commit/2ee04c52a6d6c0a98448fa80781c1df06f964ebc

**Comment by sunflowermans** [comment]
Cheers! Open up a pull request against master with just the alpha changes and I'll merge them in. 
I'll pull in rotation code when it works. Thanks for the attempt!

**Comment by RedKrieg** [comment]
PR #3 created with just the Alpha info!

**Comment by sunflowermans** [comment]
Merged. Thanks!
