### ISSUE TITLE
Tabletop Simulator crashes after recall

### ISSUE THREAD

**Issue by BakeSloth** [sunflowermans/TTS-UtilityMemoryBag#8]
Set up and started using this bag script in a game I'm working on, and it keeps crashing Tabletop after I hit Recall.

**Comment by sunflowermans** [comment]
Could you share the game file and repro steps, please? @BakeSloth

**Comment by BakeSloth** [comment]
The issue is being caused by a game piece I made by combining 4 objects into a single object, which I then created 4 different states for. I have 4 other pieces that are built the same way, except using different models. Only one of those models is causing the crash after the recall. If I don't include this game piece in the memory bag, no crash. Seems to be something unique to my game piece. closing issue.

**Comment by BakeSloth** [comment]
This is SUCH a great tool, thank you so much for making it!
